graphql:
  packages:
    - "com.example.demo"

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/test"
    username: root
    password: root
  data:
    mongodb:
      database: graphql-kotlin
      port: 27017

#jpa:
#  hibernate:
#    ddl-auto: create-drop
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect

